FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y ruby-full git curl build-essential
RUN gem install cocoapods -v 1.10.0 

WORKDIR /workspace/source

CMD pod install --allow-root && cat Podfile.lock
