//
//  Copyright (c) 2017 Emarsys. All rights reserved.
//
#import "EMSRequestModelBuilder.h"

#define REQUEST_TABLE_NAME @"request"
#define REQUEST_COLUMN_NAME_REQUEST_ID @"request_id"
#define REQUEST_COLUMN_NAME_METHOD @"method"
#define REQUEST_COLUMN_NAME_URL @"url"
#define REQUEST_COLUMN_NAME_HEADERS @"headers"
#define REQUEST_COLUMN_NAME_PAYLOAD @"payload"
#define REQUEST_COLUMN_NAME_TIMESTAMP @"timestamp"
#define REQUEST_COLUMN_NAME_EXPIRY @"expiry"

#define SHARD_TABLE_NAME @"shard"
#define SHARD_COLUMN_NAME_CATEGORY @"category"
#define SHARD_COLUMN_NAME_TIMESTAMP @"timestamp"
#define SHARD_COLUMN_NAME_TTL @"ttl"
#define SHARD_COLUMN_NAME_DATA @"data"

#define SQL_INSERT [NSString stringWithFormat:@"INSERT INTO %@ (%@, %@, %@, %@, %@, %@, %@) VALUES (?, ?, ?, ?, ?, ?, ?);", REQUEST_TABLE_NAME, REQUEST_COLUMN_NAME_REQUEST_ID, REQUEST_COLUMN_NAME_METHOD, REQUEST_COLUMN_NAME_URL, REQUEST_COLUMN_NAME_HEADERS, REQUEST_COLUMN_NAME_PAYLOAD, REQUEST_COLUMN_NAME_TIMESTAMP, REQUEST_COLUMN_NAME_EXPIRY]
#define SQL_SELECTFIRST [NSString stringWithFormat:@"SELECT * FROM %@ ORDER BY ROWID ASC LIMIT 1;", REQUEST_TABLE_NAME]
#define SQL_SELECTALL [NSString stringWithFormat:@"SELECT * FROM %@ ORDER BY ROWID ASC;", REQUEST_TABLE_NAME]
#define SQL_DELETE_ITEM [NSString stringWithFormat:@"DELETE FROM %@ WHERE %@ = ?;", REQUEST_TABLE_NAME, REQUEST_COLUMN_NAME_REQUEST_ID]
#define SQL_DELETE_MULTIPLE_ITEM(ids) [NSString stringWithFormat:@"DELETE FROM %@ WHERE %@ IN (%@);", REQUEST_TABLE_NAME, REQUEST_COLUMN_NAME_REQUEST_ID, ids]
#define SQL_PURGE [NSString stringWithFormat:@"DELETE FROM %@;", REQUEST_TABLE_NAME]
#define SQL_COUNT [NSString stringWithFormat:@"SELECT COUNT(*) FROM %@;", REQUEST_TABLE_NAME]


#define SCHEMA_UPGRADE_FROM_0_TO_1 @"CREATE TABLE IF NOT EXISTS request (request_id TEXT,method TEXT,url TEXT,headers BLOB,payload BLOB,timestamp REAL);"
#define SCHEMA_UPGRADE_FROM_1_TO_2 [NSString stringWithFormat:@"ALTER TABLE request ADD COLUMN expiry DOUBLE DEFAULT %f", DEFAULT_REQUESTMODEL_EXPIRY ]
#define SCHEMA_UPGRADE_FROM_2_TO_3 @"CREATE TABLE IF NOT EXISTS shard (type TEXT,timestamp REAL,ttl REAL,data BLOB);"


#define MIGRATION @[SCHEMA_UPGRADE_FROM_0_TO_1,SCHEMA_UPGRADE_FROM_1_TO_2,SCHEMA_UPGRADE_FROM_2_TO_3]