//
//  Copyright (c) 2017 Emarsys. All rights reserved.
//
#import "EMSRequestModelBuilder.h"
#import "MEDisplayedIAMContract.h"
#import "MEButtonClickContract.h"

#define REQUEST_TABLE_NAME @"request"
#define REQUEST_COLUMN_NAME_REQUEST_ID @"request_id"
#define REQUEST_COLUMN_NAME_METHOD @"method"
#define REQUEST_COLUMN_NAME_URL @"url"
#define REQUEST_COLUMN_NAME_HEADERS @"headers"
#define REQUEST_COLUMN_NAME_PAYLOAD @"payload"
#define REQUEST_COLUMN_NAME_TIMESTAMP @"timestamp"
#define REQUEST_COLUMN_NAME_EXPIRY @"expiry"

#define SHARD_TABLE_NAME @"shard"
#define SHARD_COLUMN_NAME_TYPE @"type"
#define SHARD_COLUMN_NAME_SHARD_ID @"shard_id"
#define SHARD_COLUMN_NAME_TIMESTAMP @"timestamp"
#define SHARD_COLUMN_NAME_TTL @"ttl"
#define SHARD_COLUMN_NAME_DATA @"data"

#define SQL_REQUEST_INSERT [NSString stringWithFormat:@"INSERT INTO %@ (%@, %@, %@, %@, %@, %@, %@) VALUES (?, ?, ?, ?, ?, ?, ?);", REQUEST_TABLE_NAME, REQUEST_COLUMN_NAME_REQUEST_ID, REQUEST_COLUMN_NAME_METHOD, REQUEST_COLUMN_NAME_URL, REQUEST_COLUMN_NAME_HEADERS, REQUEST_COLUMN_NAME_PAYLOAD, REQUEST_COLUMN_NAME_TIMESTAMP, REQUEST_COLUMN_NAME_EXPIRY]
#define SQL_REQUEST_SELECTFIRST [NSString stringWithFormat:@"SELECT * FROM %@ ORDER BY ROWID ASC LIMIT 1;", REQUEST_TABLE_NAME]
#define SQL_REQUEST_SELECTALL [NSString stringWithFormat:@"SELECT * FROM %@ ORDER BY ROWID ASC;", REQUEST_TABLE_NAME]
#define SQL_REQUEST_DELETE_ITEM [NSString stringWithFormat:@"DELETE FROM %@ WHERE %@ = ?;", REQUEST_TABLE_NAME, REQUEST_COLUMN_NAME_REQUEST_ID]
#define SQL_REQUEST_DELETE_MULTIPLE_ITEM(ids) [NSString stringWithFormat:@"DELETE FROM %@ WHERE %@ IN (%@);", REQUEST_TABLE_NAME, REQUEST_COLUMN_NAME_REQUEST_ID, ids]
#define SQL_REQUEST_PURGE [NSString stringWithFormat:@"DELETE FROM %@;", REQUEST_TABLE_NAME]
#define SQL_REQUEST_COUNT [NSString stringWithFormat:@"SELECT COUNT(*) FROM %@;", REQUEST_TABLE_NAME]

#define SQL_SHARD_INSERT [NSString stringWithFormat:@"INSERT INTO %@ (%@, %@, %@, %@, %@) VALUES (?, ?, ?, ?, ?);", SHARD_TABLE_NAME, SHARD_COLUMN_NAME_SHARD_ID, SHARD_COLUMN_NAME_TYPE, SHARD_COLUMN_NAME_DATA, SHARD_COLUMN_NAME_TIMESTAMP, SHARD_COLUMN_NAME_TTL]
#define SQL_SHARD_SELECTALL [NSString stringWithFormat:@"SELECT * FROM %@ ORDER BY ROWID ASC;", SHARD_TABLE_NAME]
#define SQL_SHARD_SELECTLAST [NSString stringWithFormat:@"SELECT * FROM %@ ORDER BY ROWID DESC LIMIT 1;", SHARD_TABLE_NAME]
#define SQL_SHARD_SELECT_BY_TYPE(type) [NSString stringWithFormat:@"SELECT * FROM %@ WHERE %@ LIKE '%@' ORDER BY ROWID ASC;", SHARD_TABLE_NAME, SHARD_COLUMN_NAME_TYPE, type]
#define SQL_SHARD_DELETE_MULTIPLE_ITEM(ids) [NSString stringWithFormat:@"DELETE FROM %@ WHERE %@ IN (%@);", SHARD_TABLE_NAME, SHARD_COLUMN_NAME_SHARD_ID, ids]
#define SQL_SHARD_COUNT [NSString stringWithFormat:@"SELECT COUNT(*) FROM %@;", SHARD_TABLE_NAME]

#define SCHEMA_UPGRADE_FROM_0_TO_1 @[[NSString stringWithFormat:\
@"CREATE TABLE IF NOT EXISTS request (request_id TEXT,method TEXT,url TEXT,headers BLOB,payload BLOB,timestamp REAL, expiry DOUBLE DEFAULT %f);", DEFAULT_REQUESTMODEL_EXPIRY], \
@"CREATE TABLE IF NOT EXISTS shard (shard_id TEXT,type TEXT,data BLOB,timestamp REAL,ttl REAL);",\
@"CREATE INDEX shard_id_index ON shard (shard_id);",\
@"CREATE INDEX shard_type_index ON shard (type);",\
SQL_CREATE_TABLE_DISPLAYED_IAM,\
SQL_CREATE_TABLE_BUTTON_CLICK]

#define SCHEMA_UPGRADE_SET_VERSION(version) [NSString stringWithFormat:@"PRAGMA user_version=%d;", version]

#define MIGRATION @[SCHEMA_UPGRADE_FROM_0_TO_1]