platform :ios, '11.0'
use_frameworks!

target "Emarsys-Sample" do
  pod 'GoogleSignIn'
  if ENV["DEV"] then
    pod 'EmarsysSDK', :path => '../'
  else
    pod 'EmarsysSDK', :git => 'https://github.com/emartech/ios-emarsys-sdk.git'
  end
end

target "NotificationService" do
  if ENV["DEV"] then
    pod 'EmarsysNotificationService', :path => '../'
  else
    pod 'EmarsysNotificationService', :git => 'https://github.com/emartech/ios-emarsys-sdk.git'
  end
end
