platform :ios, '9.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:emartech/pod-private.git'

target "Emarsys Sample" do
    pod 'EmarsysSDK'
end

target "EMSNotificationService" do
    pod 'EmarsysNotificationService'
end

target "Emarsys SampleUITests" do
  pod 'Kiwi'
end
