name: Last commit build - Swift
on:
  push:
    branches: [ swift ]
  workflow_dispatch:
env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Remove old directories
        run: rm -rf ~/tmp | rm -rf ~/Library/MobileDevice
        shell: bash
      - name: Build And Test
        run: xcodebuild -scheme EmarsysSDK test -destination "platform=iOS Simulator,name=iPhone 15,OS=latest"
        shell: bash
      - if: ${{ failure() }}
        name: Slack Notification On Error
        uses: megamegax/slack_action@0.3.1
        with:
          webhook_url: '${{env.SLACK_WEBHOOK}}'
          actions: '[{ "type": "button", "text": "View actions", "url": "https://github.com/emartech/ios-emarsys-sdk/actions" }]'
          channel: ${{ secrets.SLACK_CHANNEL }}
          job_status: failure
          message: 'Last push build failed! :sob:'
          user_icon: 'https://img.pngio.com/rotten-apple-png-images-vectors-and-psd-files-free-download-on-png-rotten-apple-260_391.png'
          user_name: Emarsys SDK - iOS
      - if: ${{ !failure() }}
        name: Slack Notification On Success
        uses: megamegax/slack_action@0.3.1
        with:
          webhook_url: '${{env.SLACK_WEBHOOK}}'
          actions: '[{ "type": "button", "text": "View actions", "url": "https://github.com/emartech/ios-emarsys-sdk/actions" }]'
          channel: ${{ secrets.SLACK_CHANNEL }}
          job_status: 'success'
          message: 'Last push build successful! :man-gesturing-ok: :bananadance:'
          user_icon: 'https://www.apple.com/ac/structured-data/images/knowledge_graph_logo.png'
          user_name: Emarsys SDK - iOS
