name: New tag triggered build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  CreateJiraTicket:
    name: Create Jira ticket
    runs-on: ubuntu-latest
    steps:
      - name: Login to Jira
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: setup RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create a ticket
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: ${{ secrets.JIRA_PROJECT }}
          issuetype: Product docs
          fields: ${{ secrets.JIRA_TICKET_JSON }}
          summary: |
            New Emarsys SDK release on iOS
          description: |
            Emarsys SDK ${{ env.RELEASE_VERSION }} has been released!
